// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: attendees.sql

package queries

import (
	"context"
)

const createAttendee = `-- name: CreateAttendee :one
INSERT INTO attendees (
  user_id
) VALUES (
  $1
)
RETURNING attendee_id, user_id, order_id, created_at
`

func (q *Queries) CreateAttendee(ctx context.Context, userID int64) (Attendee, error) {
	row := q.db.QueryRow(ctx, createAttendee, userID)
	var i Attendee
	err := row.Scan(
		&i.AttendeeID,
		&i.UserID,
		&i.OrderID,
		&i.CreatedAt,
	)
	return i, err
}
