// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: organisers.sql

package queries

import (
	"context"
)

const createOrganiser = `-- name: CreateOrganiser :one
INSERT INTO organisers (
  user_id,event_id
) VALUES (
  $1, $2
)
RETURNING organiser_id, user_id, event_id, created_at
`

type CreateOrganiserParams struct {
	UserID  int64
	EventID int64
}

func (q *Queries) CreateOrganiser(ctx context.Context, arg CreateOrganiserParams) (Organiser, error) {
	row := q.db.QueryRow(ctx, createOrganiser, arg.UserID, arg.EventID)
	var i Organiser
	err := row.Scan(
		&i.OrganiserID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}
