// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ticket.sql

package queries

import (
	"context"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
  ticket_type_id
) VALUES (
  $1
)
RETURNING ticket_id, ticket_type_id
`

func (q *Queries) CreateTicket(ctx context.Context, ticketTypeID int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, ticketTypeID)
	var i Ticket
	err := row.Scan(&i.TicketID, &i.TicketTypeID)
	return i, err
}
