// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ticket-order.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicketOrder = `-- name: CreateTicketOrder :one
INSERT INTO ticket_orders (
  attendee_id
) VALUES (
  $1
)
RETURNING order_id, payment_id, created_at, attendee_id, total_amount
`

func (q *Queries) CreateTicketOrder(ctx context.Context, attendeeID pgtype.Int8) (TicketOrder, error) {
	row := q.db.QueryRow(ctx, createTicketOrder, attendeeID)
	var i TicketOrder
	err := row.Scan(
		&i.OrderID,
		&i.PaymentID,
		&i.CreatedAt,
		&i.AttendeeID,
		&i.TotalAmount,
	)
	return i, err
}

const updateTotalAmountOrder = `-- name: UpdateTotalAmountOrder :exec
UPDATE ticket_orders 
  set total_amount = $2
  
WHERE order_id = $1
`

type UpdateTotalAmountOrderParams struct {
	OrderID     int64
	TotalAmount pgtype.Numeric
}

func (q *Queries) UpdateTotalAmountOrder(ctx context.Context, arg UpdateTotalAmountOrderParams) error {
	_, err := q.db.Exec(ctx, updateTotalAmountOrder, arg.OrderID, arg.TotalAmount)
	return err
}
