// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ticket_types.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicketType = `-- name: CreateTicketType :one
INSERT INTO ticket_types (
  name,price,total_tickets
) VALUES (
  $1, $2, $3
)
RETURNING ticket_type_id, name, price, total_tickets
`

type CreateTicketTypeParams struct {
	Name         pgtype.Text
	Price        pgtype.Numeric
	TotalTickets int32
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, createTicketType, arg.Name, arg.Price, arg.TotalTickets)
	var i TicketType
	err := row.Scan(
		&i.TicketTypeID,
		&i.Name,
		&i.Price,
		&i.TotalTickets,
	)
	return i, err
}
